### DISCUSSION TITLE
表格固定列和固定表头的border消失

### DISCUSSION THREAD

**Discussion by hzlzsm** [Tencent/tdesign-vue-next#5566] [Q&A] [answered]
![image](https://github.com/user-attachments/assets/42e8d9d2-ba90-45ba-beb3-ca85ff34808c)
![测试](https://github.com/user-attachments/assets/02012141-6f73-4d5f-92c9-d5361944498c)

如上图，表格设置了固定列，但是固定列的border在初始位置上有的，一旦横向滚动后，border就会随滚动条滚动。但是在sandbox里一样的数据结构，又是正常的。有什么因素会导致出现这种问题

**Comment by hzlzsm** [comment]
沙盒里显示是正常的，https://codesandbox.io/p/devbox/tdesign-table-test-vkt4ww
我不知道为什么在项目里会出现border滚动现象。因为今天第一天使用tdesign，不知道有什么解决方法

**Comment by hzlzsm** [comment]
查看issue，感觉可能跟https://github.com/Tencent/tdesign-vue-next/issues/5260#issue-2963295086
的原因一样

**Comment by hzlzsm** [comment, marked as answer]
zoom和border-collapse设置都试过了，没什么效果。最后采用了outline的解决方法，这个方法也有弊端，表格固定头和下面表格会有1px的错位
```css
.t-table__header--fixed > tr > th {
    outline: 1px solid var(--td-component-border);
    border-left: none;
    border-bottom: none;
  }
  .t-table__cell--fixed-left,
  .t-table__cell--fixed-right {
    outline: 1px solid var(--td-component-border);
    border-left: none;
    border-bottom: none;
  }
```

![image](https://github.com/user-attachments/assets/c8c84258-8b57-42a3-ba0e-df79c01da579)

或者表格的单元格都用outline，取消border，这样就没有1px错位
```css
.t-table th,
.t-table td {
    outline: 1px solid var(--td-component-border);
    border-left: none;
    border-bottom: none;
}
```

提问我就不删除了，留一个方案参考吧
