### ISSUE TITLE
[Loading] v-loading 指令如何设置loading 大小

### ISSUE THREAD

**Issue by Joycezhangw** [Tencent/tdesign-vue-next#3350]
### 这个功能解决了什么问题

我在很小的区域使用 `v-loading` 指令，但是 loading 展示出来太大了。

### 你建议的方案是什么

可以全局配置loading大小

**Comment by uyarn** [comment]
直接在你用v-loading的地方改下font-size就可以了 loading里面是1em的svg 会跟随字体大小变化。
e.g.,
```less
.container {
  .t-loading {
    font-size: 12px;
   }
}
```
