### ISSUE TITLE
[Menu] 可分组的侧边导航收起样式调整

### ISSUE THREAD

**Issue by RayJason** [Tencent/tdesign-vue-next#3533]
### 这个功能解决了什么问题

当前收起后组名会变成一条 灰色分割线，第一条分割线显得有点多余。并且 logo 的左边距过大，导致偏右。

![image](https://github.com/Tencent/tdesign-vue-next/assets/15711610/ac7334ab-ced8-40d8-9f54-c7a9da6be06f)

### 你建议的方案是什么

调整收起后 logo 的 margin；不显示第一个分割线，之前在组名 title 上使用 after  伪类实现，后面考虑使用 t-divider 实现分割线。

![image](https://github.com/Tencent/tdesign-vue-next/assets/15711610/08f15ee5-d0ae-441b-9249-b49d07fd9bb1)

**Comment by RayJason** [comment]
1. item 前面有个 title ，导致这个 first-child 不生效
 2. `t-menu-group` 内有 `t-menu-group__title`、 `t-submenu`、`t-menu__item`，这里的 margin 实现方式不是很优雅，期望改成 
 ```scss
 t-menu-group >  *:not(:first-child) {
  margin-top: var(--td-comp-margin-xs);
}
```
![image](https://github.com/Tencent/tdesign-vue-next/assets/15711610/90ddb10a-7b8c-463f-81e4-e22cab39049b)
