### ISSUE TITLE
表格的表头，背景颜色可以改变吗？

### ISSUE THREAD

**Issue by tiantiankexiao** [Tencent/tdesign-vue-next#3597]
### 这个功能解决了什么问题

我想改变表头行的背景颜色

### 你建议的方案是什么

如果能，告知一下

**Comment by chaishi** [comment]
```html
<t-table class="t-table--custom" />
```

```css
.t-table.t-table--custom table > thead > tr > th {
    background-color: var(--td-bg-color-secondarycontainer);
}
```

<img width="1176" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/538671fe-5e9e-4f94-b829-717c00348cf1">
