### ISSUE TITLE
t-textures 如何撑满高度并固定？

### ISSUE THREAD

**Issue by iibrat** [Tencent/tdesign-vue-next#3630]
我想让textarea 高度撑满，而不是随着内容到增加而增高，尝试了好多次都没有成功，有人知道如何实现吗？

**Comment by wenkeming** [comment]
如果设置多少行的话，把`minRows`和`maxRows`设置成一样的。如果要设置具体高度可以通过样式设置`height`
```less
.t-textarea{
    height: 200px;
    &__inner{
        height: 100%;
    }
}

```
