### ISSUE TITLE
[Collapse] 增加transition参数

### ISSUE THREAD

**Issue by p7e4rs** [Tencent/tdesign-vue-next#4822]
### 这个功能解决了什么问题

增加一个transition参数控制展开折叠时是否使用过渡动画

### 你建议的方案是什么

rt

**Comment by wenkeming** [comment]
可以手动设置下
```css
.t-slide-down-enter-active,.t-slide-down-leave-active{
  transition: none;
}
```
