### ISSUE TITLE
[AiChat] 在引入 ai 组件时会覆盖自定义 css 变量

### ISSUE THREAD

**Issue by Hiram-Wong** [Tencent/tdesign-vue-next#4948]
### tdesign-vue-next 版本

1.10.6

### 重现步骤

main.js
```js
import { createApp } from 'vue';

import App from './App.vue';
import router from './router';
import { store } from './store';
import i18n from './locales';

import 'tdesign-vue-next/es/style/index.css';
import '@/style/index.less';

import { Tooltip as TTooltip } from 'tdesign-vue-next';

const app = createApp(App);

app.use(store);
app.use(router);
app.use(i18n);
app.use(TTooltip);

app.mount('#app');
```

index.less中自定义了
```less
:root,:root[theme-mode="light"] {
  --td-font-family: MiSans;
  --td-font-family-medium: MiSans;
  --td-brand-color-light: var(--td-brand-color-1);
  --td-brand-color-focus: var(--td-brand-color-2);
  --td-brand-color-disabled: var(--td-brand-color-3);
  --td-brand-color-hover: var(--td-brand-color-3);
  --td-brand-color: var(--td-brand-color-4);
  --td-brand-color-active: var(--td-brand-color-5);
  --td-brand-color-1: #e4f9e9;
  --td-brand-color-2: #c8f2d7;
  --td-brand-color-3: #94dab2;
  --td-brand-color-4: #45c58b;
  --td-brand-color-5: #33a371;
  --td-brand-color-6: #008857;
  --td-brand-color-7: #006c44;
  --td-brand-color-8: #005333;
  --td-brand-color-9: #003b23;
  --td-brand-color-10: #002515;
  --td-radius-default: var(--td-radius-medium);
}

:root[theme-mode='dark'] {
  --td-brand-color-light: var(--td-brand-color-1);
  --td-brand-color-focus: var(--td-brand-color-2);
  --td-brand-color-disabled: var(--td-brand-color-3);
  --td-brand-color-hover: var(--td-brand-color-5);
  --td-brand-color: var(--td-brand-color-6);
  --td-brand-color-active: var(--td-brand-color-7);
  --td-brand-color-1: #33a37120;
  --td-brand-color-2: #003b23;
  --td-brand-color-3: #005333;
  --td-brand-color-4: #006c44;
  --td-brand-color-5: #008857;
  --td-brand-color-6: #33a371;
  --td-brand-color-7: #45c58b;
  --td-brand-color-8: #94dab2;
  --td-brand-color-9: #c8f2d7;
  --td-brand-color-10: #e4f9e9;
}

```

组件
```js
import {
  Chat as TChat,
  ChatAction as TChatAction,
  ChatContent as TChatContent,
  ChatInput as TChatInput,
  ChatItem as TChatItem,
} from '@tdesign-vue-next/chat';
```

导入ai 组件后，会覆盖掉我的自定义颜色变量 都变成蓝色了
导入 ai 组件前
<img width="414" alt="Image" src="https://github.com/user-attachments/assets/86056e68-ee0d-44e5-806f-68c53c0d795e" />

导入ai 组件后后
<img width="331" alt="Image" src="https://github.com/user-attachments/assets/33d7c009-f3b2-488b-af7f-d6717625dd4f" />

### 期望结果

修复颜色覆盖问题
