### ISSUE TITLE
[Table] 火狐浏览器中，TableCol 的 minWidth 属性无效

### ISSUE THREAD

**Issue by QAQCup** [Tencent/tdesign-vue-next#4997]
### tdesign-vue-next 版本

1.10.7

### 重现链接

https://stackblitz.com/edit/gexcquk2-ojswqh3v?file=package.json,src%2Fdemo.vue

### 重现步骤

![Image](https://github.com/user-attachments/assets/4971f49b-9b85-4987-88cf-faa15b2b1fdb)

**Comment by QAQCup** [comment]
怎么可以判断一下，在不支持minWidth的浏览器中，自动将minWidth属性改为width呢？

**Comment by YuShengHou** [comment]
@QAQCup 
> 怎么可以判断一下，在不支持minWidth的浏览器中，自动将minWidth属性改为width呢？

# 方式一（推荐）：同时设置width和minWidth
```ts
// ...省略代码
const columns: TableProps["columns"] = [
    // ...省略代码
    colKey: "detail.email",
    title: "邮箱地址",
    minWidth: 120,
    width: 120,
]
// ...省略代码
```

# 方式二： hack
```ts
// ...省略代码
const columns: TableProps["columns"] = [
    // ...省略代码
    colKey: "detail.email",
    title: "邮箱地址",
    minWidth: "120",
    // 增加自定义样式类
    className: "min-width-class",
]
// ...省略代码
```

```css
/* 仅火狐浏览器生效的样式 */
@-moz-document url-prefix() {
  .min-width-class {
    min-width: 120px;
    width: 120px;
    color: rebeccapurple;
  }
}
```

<img width="671" height="479" alt="Image" src="https://github.com/user-attachments/assets/79c2986e-2611-40dc-9091-cf6745b4d9d4" />
