### ISSUE TITLE
[组件名称] ConfigProvider animation 动画排除无效

### ISSUE THREAD

**Issue by ankyo** [Tencent/tdesign-vue-next#5487]
### tdesign-vue-next 版本

1.13.0

### 重现链接

比较简单不用重现

### 重现步骤

比较简单不用重现

### 期望结果

```ts
const globalConfig: TdConfigProviderProps['globalConfig'] = {
  animation: {
    exclude: ['ripple', 'expand', 'fade'],
  },
}
```

期望是关闭所有组件动画，每个组件库基本上都要设一个全局开关，几乎每个都有关闭动画的需求，动画除了花里胡哨没半点用处，还多费点电，另外还影响到客户机卡顿

### 实际结果

实际上是组件还是老样子，目前还不了解排除这三个动画效果影响的是哪里

**Comment by ankyo** [comment]
补充一下，覆盖样式方式去动画有副作用，关闭时有延迟，是否这个延迟是动画的运动时间？

```less
.t-dialog {
  animation: none !important;
  &__mask {
    animation: none !important;
  }
}
```
